### ISSUE TITLE
Non-wrapping calls to gaussian in sketch code

### ISSUE THREAD

**Issue by dalpil** [laszlokorte/blue-noise#1]
Firstly, thank you for providing such a clear and concise explanation of the void-and-cluster method for generating blue noise. Your visualization made it immediately clear how the algorithm functions.

Regarding the issue, it appears that all the images were produced using a wrapping Gaussian filter, yet the provided "sketch-code" employs a Gaussian call without border wrapping. This could potentially mislead readers, as it produces lower-quality noise with border artifacts that are clearly visible when tiled.

For clarity, I suggest modifying the Gaussian function calls from `gaussian(placed_pixels, sigma)` to `gaussian(placed_pixels, sigma, mode='wrap')`.

**Comment by laszlokorte** [comment]
Thanks for your feedback! I am glad you find the visualization helpful.

You are right, the images are generated with `mode='wrap'` but in the presented code this is omitted.
My reasoning was that I wanted the presented code to be as succinct as possible without too much clutter.
Also I am not sure if wrapping is *generally* the only correct option or if there are use cases for which other modes are appropriate.

Finally I agree that the code should be consistent with the presented output. I will fix this.

**Comment by laszlokorte** [comment]
Has been fixed with 554e5de9f
